<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="FALCA E-Solutions" duration-ms="29447" started-at="2019-09-17T07:55:50Z" finished-at="2019-09-17T07:56:19Z">
    <groups>
    </groups>
    <test name="FALCA" duration-ms="29447" started-at="2019-09-17T07:55:50Z" finished-at="2019-09-17T07:56:19Z">
      <class name="Script.jenkin">
        <test-method status="PASS" signature="openApplication()[pri:0, instance:Script.jenkin@564718df]" name="openApplication" is-config="true" duration-ms="14202" started-at="2019-09-17T13:25:50Z" finished-at="2019-09-17T13:26:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method status="FAIL" signature="google()[pri:0, instance:Script.jenkin@564718df]" name="google" duration-ms="14378" started-at="2019-09-17T13:26:04Z" finished-at="2019-09-17T13:26:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [B] but found [Basavaraj Thilagar]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [B] but found [Basavaraj Thilagar]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at POM.googleLoginPage.span(googleLoginPage.java:35)
	at Script.jenkin.google(jenkin.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- google -->
        <test-method status="PASS" signature="closeApplication()[pri:0, instance:Script.jenkin@564718df]" name="closeApplication" is-config="true" duration-ms="832" started-at="2019-09-17T13:26:19Z" finished-at="2019-09-17T13:26:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- Script.jenkin -->
    </test> <!-- FALCA -->
  </suite> <!-- FALCA E-Solutions -->
</testng-results>
